### PR TITLE
Add support for logfile rotation

### PR DESCRIPTION
**Pull request by justintime32**
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/go-audit/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/slackhq/go-audit/blob/master/CODE_OF_CONDUCT.md).
* [x] I've been mindful about doing atomic commits, adding documentation to my changes, not refactoring too much.
* [x] I've a descriptive title and added any useful information for the reviewer. Where appropriate, I've attached a screenshot and/or screencast (gif preferrably).
* [x] I've written tests to cover the new code and functionality included in this PR.
* [x] I've read, agree to, and signed the [Contributor License Agreement (CLA)](https://docs.google.com/a/slack-corp.com/forms/d/1q_w8rlJG_x_xJOoSUMNl7R35rkpA7N6pUkKhfHHMD9c/viewform).

#### PR Summary

Currently, when using the file output module, there is no clean way to rotate the log file it produces. This is especially important for audit log messages, which can grow very large over time.

This change will trap a USR1 signal and re-open the log file upon receipt of the signal. The intention is for this to be used along with logrotate. I've also included a sample logrotate configuration that works with it.

I've additionally changed the log file location in the example conf to /var/log/go-audit/go-audit.log, and changed the ownership to root/root (which is important since audit logs often contain sensitive information).

### CODE REVIEW

**Comment by justintime32** [comment]
Any thoughts on this change?

**Comment by justintime32** [comment]
_bump_

**Comment by mwielgoszewski** [comment]
Does `copytruncate` not work here?

**Comment by justintime32** [comment]
@nbrownus copytruncate can work but has some important drawbacks. Using copytruncate can cause issues with log tailing agents (e.g. filebeat). Such agents commonly track log offsets based on inode and cannot always handle it when an existing log file shrinks. It also can cause rotated logs to be re-read since the old logs are in a new file with a new inode.

It also is less efficient when dealing with very large files since it first must copy existing logs.

**Comment by justintime32** [comment]
_bump_
Any thoughts?

**Comment by nbrownus** [comment]
The delay on this PR was largely due to discussions on the implications around futher support for storing logs locally. `go-audit` was never intended to store logs locally given their sensitive nature. 

The functionality is sound but I'd like to see the implementation move from `createOutput` to its own function and `go funcName()` in `createOutput` as well as removing the example config changes.

**Comment by justintime32** [comment]
@nbrownus I'll work on the code refactor and will have a new commit shortly.

Although IMO the changes to the example config are useful. I think that a location under `/var/log` is a reasonably sensible default, and the file output is still shut off in the example.

**Pull request merged**
